/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio3;

import javax.swing.JOptionPane;

/**
 *
 * @author SP
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio3
     */ 
    double a[],b[],suma[],resta[];
    public Ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVectoruno = new javax.swing.JTextField();
        txtVectordos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmdResta = new javax.swing.JButton();
        cmdSuma = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("ejercicio3");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("longitud");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabel3.setText("v1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setText("v2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 20, -1));

        txtVectoruno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVectorunoKeyTyped(evt);
            }
        });
        jPanel1.add(txtVectoruno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, -1));

        txtVectordos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVectordosKeyTyped(evt);
            }
        });
        jPanel1.add(txtVectordos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 90));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("menu");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        cmdCrear.setText("crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cmdManual.setText("llenado manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel2.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        cmdAutomatico.setText("llenado automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        cmdResta.setText("resta");
        cmdResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        cmdSuma.setText("suma");
        cmdSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSumaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        cmdMostrar.setText("mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        cmdBorrar.setText("borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 270, 140));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("resultados");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 490, 170));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 510, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
     int longitud1,longitud2; 
    if(txtVectoruno.getText().trim().isEmpty()){ 
        JOptionPane.showMessageDialog(this,"Ingrese longitud del vector uno","Error",JOptionPane.ERROR_MESSAGE); 
        txtVectoruno.requestFocusInWindow();
    }else if(txtVectordos.getText().trim().isEmpty()){ 
       JOptionPane.showMessageDialog(this,"Ingrese longitud del vector dos","Error",JOptionPane.ERROR_MESSAGE); 
       txtVectordos.requestFocusInWindow();
    }else if(Integer.parseInt(txtVectoruno.getText().trim())==0){ 
       JOptionPane.showMessageDialog(this,"La longitud del vector no puede ser cero","Error",JOptionPane.ERROR_MESSAGE); 
       txtVectoruno.requestFocusInWindow(); 
       txtVectoruno.selectAll();
    }else if(Integer.parseInt(txtVectordos.getText().trim())==0){ 
       JOptionPane.showMessageDialog(this,"La longitud del vector no puede ser cero","Error",JOptionPane.ERROR_MESSAGE); 
       txtVectordos.requestFocusInWindow(); 
       txtVectordos.selectAll();
    }else{ 
      longitud1=Integer.parseInt(txtVectoruno.getText()); 
      longitud2=Integer.parseInt(txtVectordos.getText()); 
      a=new double[longitud1]; 
      b=new double[longitud2]; 
      JOptionPane.showMessageDialog(this,"Vector creado satisfactoriamente");
    }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        double num1,num2; 
        for (int i = 0; i < a.length; i++) {
          num1=Double.parseDouble(JOptionPane.showInputDialog(this,"Ingrese el vector uno en la posicion:"+i)); 
          a[i]=num1;
        } 
        for (int i = 0; i < a.length; i++) {
          num2=Double.parseDouble(JOptionPane.showInputDialog(this,"Ingrese el vector dos en la posicion:"+i)); 
          b[i]=num2;
            
        }
        
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       a=null; 
       b=null;
       suma=null; 
       resta=null; 
       txtVectoruno.setText(""); 
       txtVectoruno.requestFocusInWindow(); 
       txtVectordos.setText(""); 
       txtResultado.setText("");
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
       double numero,numero1,numero2; 
     numero=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el numero hasta donde desee el llenado automatico")); 
     while(numero<a.length){ 
       JOptionPane.showMessageDialog(this,"Ingrese numero mayor a:"+a.length); 
      numero=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el numero hasta donde desee el llenado automatico: "));
     } 
        for (int i = 0; i < a.length; i++) {
          numero1=(int)(Math.random()*numero+1); 
          a[i]=numero1;
        } 
        while(numero<b.length){ 
          JOptionPane.showMessageDialog(this,"Ingrese numero mayor a:"+b.length); 
          numero=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el numero hasta donde desee el llenado automatico"));
        } 
        for (int i = 0; i < b.length; i++) { 
          numero2=(int)(Math.random()*numero+1); 
          b[i]=numero2; } 
         JOptionPane.showMessageDialog(this,"Vectores llenados satisfactoriamente");
            
            
        
       
      
    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void cmdSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSumaActionPerformed
        int sumavector; 
        sumavector=Integer.parseInt(txtVectoruno.getText().trim());  
        suma=new double[sumavector]; 
        for (int i = 0; i < a.length; i++) {
            suma[i]=(a[i]+b[i]);
        } 
        for (int i = 0; i < a.length; i++) {
           txtResultado.append("El resultado de la suma en la posicion "+i+" es: "+suma[i]+"\n");
            
        }
        
        
    }//GEN-LAST:event_cmdSumaActionPerformed

    private void cmdRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestaActionPerformed
        int restavector; 
       restavector=Integer.parseInt(txtVectoruno.getText().trim()); 
       resta=new double[restavector]; 
        for (int i = 0; i < a.length; i++) {
            resta[i]=(a[i]-b[i]);
        } 
        for (int i = 0; i < a.length; i++) {
            txtResultado.append("El resultado de la resta en la posicion "+i+" es: "+resta[i]+"\n");
            
        }
        
    }//GEN-LAST:event_cmdRestaActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
      txtResultado.append("Los elementos del vector 1 son:"); 
        for (int i = 0; i < a.length; i++) {
           txtResultado.append(a[i]+"\n");
        } 
        for (int i = 0; i < a.length; i++) {
           txtResultado.append("Los elementos del vector 2 son: ");
        txtResultado.append(b[i]+"\n"); 
            
        }
        
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void txtVectorunoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVectorunoKeyTyped
        char c=evt.getKeyChar(); 
        if(!Character.isDigit(c)){ 
         getToolkit().beep(); 
         evt.consume();
        }
    }//GEN-LAST:event_txtVectorunoKeyTyped

    private void txtVectordosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVectordosKeyTyped
       char c=evt.getKeyChar(); 
        if(!Character.isDigit(c)){ 
         getToolkit().beep(); 
         evt.consume(); 
        }
    }//GEN-LAST:event_txtVectordosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdResta;
    private javax.swing.JButton cmdSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtVectordos;
    private javax.swing.JTextField txtVectoruno;
    // End of variables declaration//GEN-END:variables
}
